//
//  MyStyle.m
//  SimpleProject
//
//  Created by Paolo on 09/09/2015.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "MyStyle.h"


@implementation MyStyle

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawLogoCanvasWithLogoWidth: (CGFloat)logoWidth
{
    //// Color Declarations
    UIColor* logoTextFill = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* logoSymbolFill = [UIColor colorWithRed: 0.114 green: 0.651 blue: 0.392 alpha: 1];

    //// Variable Declarations
    CGFloat logoHeight = logoWidth / 4.80;

    //// Frames
    CGRect frame = CGRectMake(0, -0, logoWidth, logoHeight);


    //// Logo 2 Drawing
    UIBezierPath* logo2Path = [UIBezierPath bezierPath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95461 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95461 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27005 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.93350 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27005 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.93350 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32439 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92013 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.93350 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35903 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92927 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.91573 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.91573 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47874 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.93139 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47874 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.93139 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65907 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95883 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77877 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.93139 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73387 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94194 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77877 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.97203 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76931 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.96569 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77877 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.96991 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.97203 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68270 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.96481 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68584 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.97079 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68427 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.96763 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68584 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95461 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64096 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.95813 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68584 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.95461 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67481 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95461 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47874 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.97203 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47874 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.97203 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95461 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85507 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85507 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55039 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.87126 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.85507 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50551 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86106 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88727 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54724 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.88252 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.88727 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50393 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88727 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.91067 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.91067 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52914 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.87935 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37558 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.91067 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44408 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.90082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37558 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85437 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43384 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.87003 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37558 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.85965 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39368 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85437 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85507 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82147 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66221 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.80194 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63623 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78223 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69530 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.79913 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67089 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.79314 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69530 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76042 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60709 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.77062 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69530 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76094 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65829 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82235 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60709 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82270 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57480 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.82235 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60552 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.82270 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58977 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.77995 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.82270 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45039 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.80669 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57796 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.73737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45433 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.73737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70868 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.75831 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82147 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66221 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.80335 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.81707 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72916 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79965 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76094 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78030 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45905 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76147 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49999 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76816 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45905 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.79965 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.79367 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45905 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.79930 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49684 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59662 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62001 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62001 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54646 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63620 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.62001 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50393 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65151 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54331 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64676 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65151 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50157 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65151 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67473 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67473 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54646 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69074 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67473 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50472 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68071 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70605 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54331 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70147 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70605 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50157 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70605 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72874 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72874 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52205 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69742 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37478 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72874 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41810 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71344 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37478 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66998 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43936 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68599 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37478 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67684 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39211 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64429 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37478 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66558 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39762 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65608 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37478 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61896 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43306 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63479 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37478 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62371 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39526 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61896 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59662 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38581 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59662 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58623 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66221 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.56670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63623 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54700 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69530 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.56389 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67089 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55791 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69530 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52518 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60709 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.53539 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69530 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52571 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65829 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58711 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60709 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58746 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57480 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.58711 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60552 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.58746 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58977 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54471 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.58746 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45039 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57145 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.50213 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57796 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52254 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.50213 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45433 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54682 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.50213 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70868 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52307 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58623 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66221 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.56811 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.58183 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72916 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.56442 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52571 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54506 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45905 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52624 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49999 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53292 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45905 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.56442 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55843 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45905 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.56406 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49684 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44495 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64568 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42490 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66537 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46096 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42595 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70948 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.43492 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49457 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65749 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.48366 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78507 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.49457 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72049 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46888 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53858 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49457 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60080 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.48594 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55433 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45656 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52677 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44865 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49212 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45181 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52283 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44865 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51102 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45973 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45353 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44865 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47008 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45357 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45353 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47398 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50551 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46958 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45353 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47328 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48267 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49351 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48582 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45955 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49245 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44408 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.48418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42718 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50079 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44091 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.42718 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43149 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45146 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61655 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42718 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55512 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.43475 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60001 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46290 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62836 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47222 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46958 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63466 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47222 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64883 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46078 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70474 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.47222 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68662 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46853 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70474 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44495 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64568 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45058 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70474 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44548 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67639 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36585 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55039 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.33999 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66773 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35142 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55984 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.33999 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59843 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36972 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78428 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.33999 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72837 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.35125 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78428 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39523 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72679 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38256 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78428 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39083 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75750 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39611 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39523 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74176 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39558 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76302 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41757 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71183 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41705 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75988 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73230 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52126 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37887 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44330 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40631 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34175 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50157 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35564 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37399 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34315 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44093 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36251 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52126 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37904 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45825 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36321 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48740 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.36884 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45825 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50865 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38890 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45825 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48109 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38714 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53623 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52205 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53307 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36585 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55039 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61655 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37465 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70632 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68505 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38450 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70632 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36339 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66143 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36708 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70632 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.36339 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68427 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37412 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61261 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36339 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63151 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.36814 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61655 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59921 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61655 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29143 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21493 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.24656 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21493 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.24656 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29477 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.33330 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61733 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31817 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77326 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.33330 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70789 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31130 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48503 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.33330 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54803 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32344 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49842 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32943 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36533 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32169 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46928 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32943 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42283 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29143 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21493 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32943 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27871 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31570 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21493 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.28773 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44565 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27049 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44565 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27049 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30627 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.28755 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30627 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30550 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37558 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.29934 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30627 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30550 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33305 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.28773 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44565 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30550 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41810 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.29881 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44565 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logo2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29019 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68270 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27049 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68270 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27049 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame))];
    [logo2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29054 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30902 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61024 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30268 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53543 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30902 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56614 * CGRectGetHeight(frame))];
    [logo2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29019 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68270 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30902 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65514 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30198 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68270 * CGRectGetHeight(frame))];
    [logo2Path closePath];
    [logoTextFill setFill];
    [logo2Path fill];


    //// Logo 3 Drawing
    UIBezierPath* logo3Path = [UIBezierPath bezierPath];
    [logo3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18723 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43833 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18728 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42032 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18230 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39757 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04000 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.02083 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41977 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.02110 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56073 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.02112 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57215 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.02108 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57980 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10434 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96000 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18750 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58023 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18723 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43833 * CGRectGetHeight(frame))];
    [logo3Path closePath];
    [logo3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03070 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43821 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10351 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.17535 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42932 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10413 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75451 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75392 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.06435 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57098 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.07277 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53250 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67489 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.15796 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42932 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.15787 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42888 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10469 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18605 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18289 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18289 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03085 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51692 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03070 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43821 * CGRectGetHeight(frame))];
    [logo3Path closePath];
    [logo3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10434 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89648 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03299 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57067 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10420 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24548 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10433 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24607 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.14399 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42902 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.13556 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46750 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10433 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32511 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.05037 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57067 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.05047 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57112 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10364 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81394 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10434 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81711 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10434 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81711 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.17748 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48308 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.17763 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56178 * CGRectGetHeight(frame))];
    [logo3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10434 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89648 * CGRectGetHeight(frame))];
    [logo3Path closePath];
    [logoSymbolFill setFill];
    [logo3Path fill];
}

+ (void)drawBubbleAreaWithBubbleWidth: (CGFloat)bubbleWidth bubbleHeight: (CGFloat)bubbleHeight
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* bubbleGradientBase = [UIColor colorWithRed: 0.742 green: 0.742 blue: 0.742 alpha: 1];

    //// Gradient Declarations
    CGFloat bubbeGradientLocations[] = {0, 1};
    CGGradientRef bubbeGradient = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)bubbleGradientBase.CGColor, (id)UIColor.whiteColor.CGColor], bubbeGradientLocations);

    //// Frames
    CGRect frame = CGRectMake(0, 0, bubbleWidth, bubbleHeight);

    //// Subframes
    CGRect frame3 = CGRectMake(CGRectGetMinX(frame) + CGRectGetWidth(frame) - 51, CGRectGetMinY(frame) + 7, 41, 44);
    CGRect frame2 = CGRectMake(CGRectGetMinX(frame) + 8, CGRectGetMinY(frame) + 8, 32, 32);
    CGRect frame4 = CGRectMake(CGRectGetMinX(frame) + CGRectGetWidth(frame) - 52, CGRectGetMinY(frame) + CGRectGetHeight(frame) - 42, 29, 34);
    CGRect frame5 = CGRectMake(CGRectGetMinX(frame) + 8, CGRectGetMinY(frame) + CGRectGetHeight(frame) - 41, 32, 32);


    //// Bezier Drawing
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame3) + 0.60976 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.52273 * CGRectGetHeight(frame3))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame3) + 0.60976 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.57182 * CGRectGetHeight(frame3)) controlPoint1: CGPointMake(CGRectGetMinX(frame3) + 0.60976 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.52273 * CGRectGetHeight(frame3)) controlPoint2: CGPointMake(CGRectGetMinX(frame3) + 0.60976 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.54011 * CGRectGetHeight(frame3))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame3) + 0.96525 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.76308 * CGRectGetHeight(frame3)) controlPoint1: CGPointMake(CGRectGetMinX(frame3) + 0.74452 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.64432 * CGRectGetHeight(frame3)) controlPoint2: CGPointMake(CGRectGetMinX(frame3) + 0.96525 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.76308 * CGRectGetHeight(frame3))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame3) + 0.60976 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.95433 * CGRectGetHeight(frame3)) controlPoint1: CGPointMake(CGRectGetMinX(frame3) + 0.96525 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.76308 * CGRectGetHeight(frame3)) controlPoint2: CGPointMake(CGRectGetMinX(frame3) + 0.74452 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.88183 * CGRectGetHeight(frame3))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame4) + 0.89655 * CGRectGetWidth(frame4), CGRectGetMinY(frame4) + 0.35294 * CGRectGetHeight(frame4)) controlPoint1: CGPointMake(CGRectGetMinX(frame3) + 0.60976 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 1.61350 * CGRectGetHeight(frame3)) controlPoint2: CGPointMake(CGRectGetMinX(frame4) + 0.89655 * CGRectGetWidth(frame4), CGRectGetMinY(frame4) + 0.35294 * CGRectGetHeight(frame4))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame4) + 0.20690 * CGRectGetWidth(frame4), CGRectGetMinY(frame4) + 0.94118 * CGRectGetHeight(frame4)) controlPoint1: CGPointMake(CGRectGetMinX(frame4) + 0.89655 * CGRectGetWidth(frame4), CGRectGetMinY(frame4) + 0.67781 * CGRectGetHeight(frame4)) controlPoint2: CGPointMake(CGRectGetMinX(frame4) + 0.58778 * CGRectGetWidth(frame4), CGRectGetMinY(frame4) + 0.94118 * CGRectGetHeight(frame4))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame5) + 0.68750 * CGRectGetWidth(frame5), CGRectGetMinY(frame5) + 0.96875 * CGRectGetHeight(frame5))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame5) + 0.06250 * CGRectGetWidth(frame5), CGRectGetMinY(frame5) + 0.34375 * CGRectGetHeight(frame5)) controlPoint1: CGPointMake(CGRectGetMinX(frame5) + 0.34232 * CGRectGetWidth(frame5), CGRectGetMinY(frame5) + 0.96875 * CGRectGetHeight(frame5)) controlPoint2: CGPointMake(CGRectGetMinX(frame5) + 0.06250 * CGRectGetWidth(frame5), CGRectGetMinY(frame5) + 0.68893 * CGRectGetHeight(frame5))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame2) + 0.06250 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.68750 * CGRectGetHeight(frame2))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame2) + 0.68750 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.06250 * CGRectGetHeight(frame2)) controlPoint1: CGPointMake(CGRectGetMinX(frame2) + 0.06250 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.34232 * CGRectGetHeight(frame2)) controlPoint2: CGPointMake(CGRectGetMinX(frame2) + 0.34232 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.06250 * CGRectGetHeight(frame2))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame3) + 0.12195 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.06818 * CGRectGetHeight(frame3))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame3) + 0.60976 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.52273 * CGRectGetHeight(frame3)) controlPoint1: CGPointMake(CGRectGetMinX(frame3) + 0.39136 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.06818 * CGRectGetHeight(frame3)) controlPoint2: CGPointMake(CGRectGetMinX(frame3) + 0.60976 * CGRectGetWidth(frame3), CGRectGetMinY(frame3) + 0.27169 * CGRectGetHeight(frame3))];
    [bezierPath closePath];
    CGContextSaveGState(context);
    [bezierPath addClip];
    UIBezierPath* bezierRotatedPath = [bezierPath copy];
    CGAffineTransform bezierTransform = CGAffineTransformMakeRotation(135*(-M_PI/180));
    [bezierRotatedPath applyTransform: bezierTransform];
    CGRect bezierBounds = CGPathGetPathBoundingBox(bezierRotatedPath.CGPath);
    bezierTransform = CGAffineTransformInvert(bezierTransform);

    CGContextDrawLinearGradient(context, bubbeGradient,
        CGPointApplyAffineTransform(CGPointMake(CGRectGetMinX(bezierBounds), CGRectGetMidY(bezierBounds)), bezierTransform),
        CGPointApplyAffineTransform(CGPointMake(CGRectGetMaxX(bezierBounds), CGRectGetMidY(bezierBounds)), bezierTransform),
        0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(bubbeGradient);
    CGColorSpaceRelease(colorSpace);
}

@end
