//
//  MyStyle.h
//  SimpleProject
//
//  Created by Paolo on 09/09/2015.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MyStyle : NSObject

// Drawing Methods
+ (void)drawLogoCanvasWithLogoWidth: (CGFloat)logoWidth;
+ (void)drawBubbleAreaWithBubbleWidth: (CGFloat)bubbleWidth bubbleHeight: (CGFloat)bubbleHeight;

@end
