//
//  FunnyStyle.h
//  FunnyFace
//
//  Created by Paolo (via PixelCut) on 08/09/2015.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface FunnyStyle : NSObject

// Drawing Methods
+ (void)drawFaceWithHappiness: (CGFloat)happiness;

@end
